rn-start:
	npx react-native start

run-android:
	npx react-native run-android

release-android:
	npx react-native run-android --variant=release

repl:
	clj -M -m krell.main -h 192.168.1.8 -co build.edn -c -r

compile:
	clj -M -m krell.main -co build.edn -c
